# Generated by Django 2.1 on 2018-09-02 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20180825_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamentry',
            name='vehicle',
            field=models.TextField(default=None, null=True),
        ),
    ]
