# Generated by Django 2.1 on 2018-09-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20180909_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='mediaFile',
            field=models.FileField(blank=True, default=None, upload_to='uploads/'),
        ),
    ]
