# Generated by Django 2.1 on 2018-09-09 15:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20180909_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
