# Generated by Django 2.1 on 2018-09-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_auto_20180909_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.FileField(blank=True, default=None, upload_to='uploads/'),
        ),
    ]
