# Generated by Django 2.1 on 2018-09-09 17:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_auto_20180909_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driver',
            name='image',
            field=models.FileField(blank=True, default='logo.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driverentry',
            name='driverNumberFormat',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='driverraceresultinfo',
            name='infoType',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driverraceresultinfo',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='driverraceresultinfo',
            name='value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teamentry',
            name='vehicle',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
