# Generated by Django 2.1 on 2018-09-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0016_auto_20180909_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.FileField(blank=True, default=None, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
