# Generated by Django 2.1 on 2018-09-09 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_raceresult_resultfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceresult',
            name='resultSoftware',
            field=models.CharField(choices=[('rFactor 2', 'rFactor 2')], default='rFactor 2', max_length=30),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='resultFile',
            field=models.FileField(blank=True, default=None, upload_to='uploads/'),
        ),
    ]
