# Generated by Django 2.1 on 2018-09-12 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_auto_20180909_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaceOverlayControlSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('controlSet', models.TextField()),
                ('race', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.Race')),
            ],
        ),
    ]
