# Generated by Django 2.1 on 2018-09-15 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_raceoverlaycontrolset'),
    ]

    operations = [
        migrations.AddField(
            model_name='raceoverlaycontrolset',
            name='cameraId',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='raceoverlaycontrolset',
            name='slotId',
            field=models.IntegerField(default=1),
        ),
    ]
