# Generated by Django 2.1 on 2018-09-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0023_team_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='password',
            field=models.TextField(default=None, null=True),
        ),
    ]
