# Generated by Django 2.1.2 on 2018-10-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0026_teamentry_vehicleimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('skinFile', models.FileField(blank=True, default=None, upload_to='uploads/')),
            ],
        ),
    ]
