# Generated by Django 2.1.2 on 2018-10-07 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='registration',
            name='season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.Season'),
        ),
        migrations.AddField(
            model_name='registration',
            name='token',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='registration',
            name='wasUploaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='registration',
            name='skinFile',
            field=models.FileField(default=None, upload_to='uploads/'),
        ),
    ]
