# Generated by Django 2.1.2 on 2018-10-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0028_auto_20181007_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='lastName',
        ),
        migrations.AlterField(
            model_name='registration',
            name='number',
            field=models.IntegerField(max_length=3),
        ),
        migrations.AlterField(
            model_name='registration',
            name='token',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
