# Generated by Django 2.1.2 on 2018-10-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_auto_20181007_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='gdprAccept',
            field=models.BooleanField(default=False),
        ),
    ]
