# Generated by Django 2.1.2 on 2018-10-07 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_registration_gdpraccept'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='copyrightAccept',
            field=models.BooleanField(default=False),
        ),
    ]
