# Generated by Django 2.1.2 on 2018-10-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_registration_copyrightaccept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='password',
        ),
        migrations.AlterField(
            model_name='registration',
            name='copyrightAccept',
            field=models.BooleanField(default=False, verbose_name='Our submission is free of copyright violations.'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gdprAccept',
            field=models.BooleanField(default=False, verbose_name='I consent the GDPR compilant processing of my submission data'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='skinFile',
            field=models.FileField(default=None, upload_to='uploads/', verbose_name='Skin file'),
        ),
    ]
