# Generated by Django 2.1.2 on 2018-10-09 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0032_auto_20181007_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeCode', models.FloatField()),
                ('opponentCar', models.CharField(default='', max_length=100)),
                ('ownCar', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=1000)),
                ('race', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.Race')),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='number',
            field=models.IntegerField(),
        ),
    ]
