# Generated by Django 2.1.2 on 2018-10-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0036_auto_20181012_2235'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rule',
            new_name='TextBlock',
        ),
    ]
