# Generated by Django 2.1.2 on 2018-10-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0037_auto_20181013_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='context',
            field=models.CharField(choices=[('about', 'About page'), ('rule', 'Reglement')], default=('about', 'About page'), max_length=30),
        ),
    ]
