# Generated by Django 2.1.2 on 2018-10-13 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0038_textblock_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblock',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.Season'),
        ),
    ]
