# Generated by Django 2.1.2 on 2018-10-13 17:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0039_auto_20181013_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.FileField(blank=True, default=None, upload_to='uploads/flags/'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='image',
            field=models.FileField(blank=True, default='logo.png', upload_to='uploads/drivers/'),
        ),
        migrations.AlterField(
            model_name='driverentry',
            name='driverNumberFormat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='mediaFile',
            field=models.FileField(blank=True, default=None, upload_to='uploads/news/'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='raceresult',
            name='resultFile',
            field=models.FileField(blank=True, default=None, upload_to='uploads/results/'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='skinFile',
            field=models.FileField(default=None, upload_to='uploads/registration/', verbose_name='Skin file'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.FileField(blank=True, default=None, upload_to='uploads/teams/'),
        ),
        migrations.AlterField(
            model_name='teamentry',
            name='vehicleImage',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/vehicles'),
        ),
        migrations.AlterField(
            model_name='textblock',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
