# Generated by Django 2.1.2 on 2018-10-14 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0040_auto_20181013_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='opponentCar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='opponent', to='frontend.DriverEntry'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='ownCar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='frontend.DriverEntry'),
        ),
    ]
