# Generated by Django 2.1.2 on 2018-10-14 09:57

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0041_auto_20181014_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='result',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
