# Generated by Django 2.1.2 on 2018-10-17 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0044_remove_raceresult_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverraceresult',
            name='raceResult',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.RaceResult'),
        ),
    ]
