# Generated by Django 2.1.2 on 2018-10-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0045_auto_20181017_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='teaser',
            field=models.TextField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.Season'),
        ),
    ]
