# Generated by Django 2.1.2 on 2018-10-21 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0046_auto_20181020_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('registration', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Registration', to='frontend.Registration')),
            ],
        ),
        migrations.AlterField(
            model_name='textblock',
            name='context',
            field=models.CharField(choices=[('about', 'About page'), ('rule', 'Reglement'), ('landing', 'Landing page')], default=('about', 'About page'), max_length=30),
        ),
    ]
