# Generated by Django 2.1.2 on 2018-10-21 08:57

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0048_registrationstatus_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='ignoreReason',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='registration',
            name='ignored',
            field=models.BooleanField(default=False),
        ),
    ]
