# Generated by Django 2.1.2 on 2018-10-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0051_season_isopen'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='teamName',
            field=models.TextField(default='', max_length=200),
        ),
    ]
