# Generated by Django 2.1.2 on 2018-10-21 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0053_auto_20181021_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='teaser',
        ),
    ]
