# Generated by Django 2.1.2 on 2018-11-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0055_auto_20181103_0855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, null=True)),
                ('filePath', models.FileField(blank=True, default=None, null=True, upload_to='uploads/files')),
            ],
        ),
    ]
