# Generated by Django 2.1.2 on 2018-11-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0057_auto_20181122_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericprivacyaccept',
            name='email',
            field=models.EmailField(default='', max_length=200, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='genericprivacyaccept',
            name='familyName',
            field=models.CharField(default='', max_length=400, verbose_name='Family name'),
        ),
        migrations.AlterField(
            model_name='genericprivacyaccept',
            name='givenName',
            field=models.CharField(default='', max_length=400, verbose_name='Given name(s)'),
        ),
        migrations.AlterField(
            model_name='genericprivacyaccept',
            name='privacyAccept',
            field=models.BooleanField(default=False, verbose_name='I give my consent'),
        ),
    ]
