# Generated by Django 2.1.2 on 2018-11-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0059_auto_20181123_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='isDraft',
            field=models.BooleanField(default=False),
        ),
    ]
