# Generated by Django 2.1.2 on 2018-11-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0062_driverofthedayvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='driverOfTheDayVote',
            field=models.BooleanField(default=False, verbose_name='Driver of the day vote'),
        ),
    ]
