# Generated by Django 2.1.2 on 2018-12-02 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0064_auto_20181201_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raceresult',
            name='resultSoftware',
        ),
    ]
