# Generated by Django 2.1.2 on 2018-12-07 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0065_remove_raceresult_resultsoftware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverofthedayvote',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.DriverEntry'),
        ),
    ]
