# Generated by Django 2.1.2 on 2018-12-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0066_auto_20181207_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='mediaFile',
            field=models.ImageField(blank=True, default=None, upload_to='uploads/news/'),
        ),
        migrations.AddField(
            model_name='textblock',
            name='orderIndex',
            field=models.IntegerField(default=0),
        ),
    ]
