# Generated by Django 2.1.2 on 2018-12-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0067_auto_20181223_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textblock',
            name='mediaFile',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads/news/'),
        ),
    ]
