# Generated by Django 2.1.2 on 2018-12-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0068_auto_20181223_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='textblock',
            name='options',
            field=models.CharField(choices=[('left-image', 'Image left'), ('right-image', 'Image right')], default=('left-image', 'Image left'), max_length=30),
        ),
    ]
