# Generated by Django 2.1.2 on 2019-01-13 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0071_auto_20190112_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.TextField(max_length=300, verbose_name='Vehicle display name')),
                ('vehicleClass', models.TextField(verbose_name='Internal name')),
            ],
        ),
        migrations.AlterField(
            model_name='registration',
            name='firstName',
            field=models.CharField(default='', max_length=200, verbose_name='Driver first name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='lastName',
            field=models.CharField(default='', max_length=200, verbose_name='Driver last name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='number',
            field=models.IntegerField(verbose_name='Car entry number'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.VehicleClass'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='teamName',
            field=models.CharField(default='', max_length=200, verbose_name='Team name'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='token',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Token (only needed if update)'),
        ),
    ]
