# Generated by Django 2.1.2 on 2019-01-13 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0074_auto_20190113_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='vehicleClass',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='frontend.VehicleClass'),
        ),
    ]
