# Generated by Django 2.1.2 on 2019-03-03 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0076_auto_20190303_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiverySubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skinFile', models.FileField(blank=True, default=None, upload_to='uploads/registration/', verbose_name='Skin file')),
                ('registrationToken', models.CharField(max_length=10)),
                ('copyrightAccept', models.BooleanField(default=False, verbose_name='Our submission is free of copyright violations.')),
            ],
        ),
        migrations.RemoveField(
            model_name='skinsubmissions',
            name='registration',
        ),
        migrations.DeleteModel(
            name='SkinSubmissions',
        ),
    ]
