# Generated by Django 2.1.2 on 2019-03-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0077_auto_20190303_1414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericPrivacyAccept',
        ),
        migrations.AlterField(
            model_name='liverysubmission',
            name='registrationToken',
            field=models.CharField(max_length=10, verbose_name='Registration token'),
        ),
    ]
