# Generated by Django 2.1.2 on 2019-03-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0078_auto_20190308_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='categories',
            field=models.ManyToManyField(to='frontend.NewsArticleCategory'),
        ),
    ]
