# Generated by Django 2.1 on 2018-08-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20180825_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='lat',
            field=models.FloatField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='long',
            field=models.FloatField(default=5, null=True),
        ),
    ]
