# Generated by Django 2.1 on 2018-09-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_teamentry_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='season',
            name='league',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='mediaFile',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
        migrations.DeleteModel(
            name='League',
        ),
    ]
